### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/10-july#1]
What are you hoping to learn these next few days?

If you're looking to follow along during our class, check out the [class manual](https://githubtraining.github.io/training-manual-gh4m). :book:

**Comment by mj580** [comment]
just curious ...

**Comment by CatherineMallinger** [comment]
Hi, 
I will need to get familiar with pushing documents into Git Hub (for the moment I only read documents from our repository)

**Comment by MPMORRIER** [comment]
I would like to see what it all about and how I will need to use this.

**Comment by jfderouaux** [comment]
Understanding, as an FA, how GitHub can be useful to me. e.g. checking if changed code as already been delivered before starting testing OR checking the code changed...

**Comment by jq326** [comment]
I'm hoping to learn about versioning and collaboration

**Comment by SteveBaston** [comment]
I would like to have an overview of what Github is about and how to use it

**Comment by FloSeguin** [comment]
I would like to learn the basis about github to be able to work on a project with IT and Product development teams

**Comment by achim3** [comment]
this is  comment from me to you

**Comment by Claire-CConti** [comment]
I would like to figure out how we can use GitHub in our work as a team support tool?

**Comment by pm700** [comment]
I am functional analyst 
I know nothing about GitHub for the moment so I am here to learn how to use it (read and push documents)

**Comment by Phil-Clearstream** [comment]
As team of functional analysts, we have many audiences for our outputs ..... if our documentation is going to be written / stored in GitHub, how do we serve our output to our audiences ? Do we review here ? Do we version control here ? What is the end-to-end GitHub view for Functional Analysts ?

**Comment by Svedapete** [comment]
I would like to learn how to work with documents

**Comment by szigorferihegyi** [comment]
Would like to get a better idea about how GitHub is meant to be used

**Comment by nj814** [comment]
I'm network administrator.
Would like to get a better idea about how GitHub is meant to be used.

**Comment by ThomasHenin** [comment]
I would like to learn how this tool can suit our document methodology

**Comment by al517** [comment]
I would like to know how I could use github as a non-developper in my FA role

**Comment by BernardVillar** [comment]
Interested how to handle documents and versioning in Github

**Comment by hd2605** [comment]
test
